import type { Bookmark, Collection, Tag, User, Tenant } from './types';

export const mockTenant: Tenant = {
  id: 't_1',
  name: "Aayan's Workspace",
  planTier: 'pro',
  maxStorageBytes: 500 * 1024 * 1024,
  createdAt: new Date('2024-01-15'),
};

export const mockUser: User = {
  id: 'u_1',
  tenantId: 't_1',
  googleSub: '123456789',
  email: 'aayan@example.com',
  displayName: 'Aayan',
  avatarUrl: null,
  createdAt: new Date('2024-01-15'),
  lastLoginAt: new Date(),
};

export const mockCollections: Collection[] = [
  {
    id: 'c_1',
    tenantId: 't_1',
    name: 'Research',
    slug: 'research',
    colorHex: '#635BFF',
    iconIdentifier: 'flask',
    isSmartCollection: false,
    filterRules: {},
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'c_2',
    tenantId: 't_1',
    name: 'Design',
    slug: 'design',
    colorHex: '#FF5500',
    iconIdentifier: 'palette',
    isSmartCollection: false,
    filterRules: {},
    createdAt: new Date('2024-01-16'),
  },
  {
    id: 'c_3',
    tenantId: 't_1',
    name: 'Engineering',
    slug: 'engineering',
    colorHex: '#34D399',
    iconIdentifier: 'code',
    isSmartCollection: false,
    filterRules: {},
    createdAt: new Date('2024-01-17'),
  },
  {
    id: 'c_4',
    tenantId: 't_1',
    name: 'Design Inspiration',
    slug: 'design-inspiration',
    colorHex: '#FBBF24',
    iconIdentifier: 'sparkles',
    isSmartCollection: false,
    filterRules: {},
    createdAt: new Date('2024-02-01'),
  },
];

export const mockTags: Tag[] = [
  { id: 'tag_1', tenantId: 't_1', name: 'react' },
  { id: 'tag_2', tenantId: 't_1', name: 'typescript' },
  { id: 'tag_3', tenantId: 't_1', name: 'design-systems' },
  { id: 'tag_4', tenantId: 't_1', name: 'ai' },
  { id: 'tag_5', tenantId: 't_1', name: 'performance' },
  { id: 'tag_6', tenantId: 't_1', name: 'rust' },
  { id: 'tag_7', tenantId: 't_1', name: 'css' },
];

export const mockBookmarks: Bookmark[] = [
  {
    id: 'b_1',
    tenantId: 't_1',
    userId: 'u_1',
    collectionId: 'c_1',
    url: 'https://react.dev/learn/thinking-in-react',
    canonicalUrl: null,
    domain: 'react.dev',
    title: 'Thinking in React — The Complete Guide',
    description: 'A step-by-step walkthrough of designing a React component tree from a mockup.',
    author: 'React Team',
    readingTimeMinutes: 12,
    mediaType: 'article',
    contentRawHtml: null,
    contentCleanMarkdown: null,
    coverImageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=minimal%20abstract%20react%20component%20tree%20diagram%20dark%20background%20orange%20accents%20clean%20modern&image_size=landscape_4_3',
    faviconUrl: null,
    assetStorageKey: null,
    status: 'inbox',
    isPinned: false,
    decayScore: 0.92,
    tags: [mockTags[0], mockTags[1]],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'b_2',
    tenantId: 't_1',
    userId: 'u_1',
    collectionId: 'c_2',
    url: 'https://www.figma.com/blog/variable-fonts/',
    canonicalUrl: null,
    domain: 'figma.com',
    title: 'Variable Fonts — The Future of Typography on the Web',
    description: 'How variable fonts work, their benefits for performance and design flexibility.',
    author: 'Figma Team',
    readingTimeMinutes: 8,
    mediaType: 'article',
    contentRawHtml: null,
    contentCleanMarkdown: null,
    coverImageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=elegant%20typography%20specimen%20variable%20font%20weights%20dark%20background%20premium%20editorial&image_size=landscape_4_3',
    faviconUrl: null,
    assetStorageKey: null,
    status: 'inbox',
    isPinned: true,
    decayScore: 0.98,
    tags: [mockTags[2], mockTags[6]],
    createdAt: new Date('2024-03-02'),
    updatedAt: new Date('2024-03-02'),
  },
  {
    id: 'b_3',
    tenantId: 't_1',
    userId: 'u_1',
    collectionId: 'c_1',
    url: 'https://arxiv.org/abs/2303.08774',
    canonicalUrl: null,
    domain: 'arxiv.org',
    title: 'GPT-4 Technical Report',
    description: 'OpenAI presents GPT-4, a large-scale multimodal model that can accept image and text inputs.',
    author: 'OpenAI',
    readingTimeMinutes: 45,
    mediaType: 'article',
    contentRawHtml: null,
    contentCleanMarkdown: null,
    coverImageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=abstract%20neural%20network%20visualization%20dark%20tech%20aesthetic%20purple%20gradient%20nodes%20connections&image_size=landscape_4_3',
    faviconUrl: null,
    assetStorageKey: null,
    status: 'active',
    isPinned: true,
    decayScore: 0.99,
    tags: [mockTags[3]],
    createdAt: new Date('2024-03-03'),
    updatedAt: new Date('2024-03-03'),
  },
  {
    id: 'b_4',
    tenantId: 't_1',
    userId: 'u_1',
    collectionId: 'c_3',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    canonicalUrl: null,
    domain: 'youtube.com',
    title: 'Building High-Performance Web Apps with Rust and WASM',
    description: 'A deep dive into compiling Rust to WebAssembly for near-native browser performance.',
    author: 'Fireship',
    readingTimeMinutes: 18,
    mediaType: 'video',
    contentRawHtml: null,
    contentCleanMarkdown: null,
    coverImageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=rust%20programming%20language%20gear%20logo%20webassembly%20circuit%20board%20dark%20tech%20background%20neon%20orange&image_size=landscape_16_9',
    faviconUrl: null,
    assetStorageKey: null,
    status: 'inbox',
    isPinned: false,
    decayScore: 0.85,
    tags: [mockTags[5], mockTags[4]],
    createdAt: new Date('2024-03-04'),
    updatedAt: new Date('2024-03-04'),
  },
  {
    id: 'b_5',
    tenantId: 't_1',
    userId: 'u_1',
    collectionId: 'c_2',
    url: 'https://tailwindcss.com/blog/tailwindcss-v4',
    canonicalUrl: null,
    domain: 'tailwindcss.com',
    title: 'Tailwind CSS v4 — A New Era of Utility-First CSS',
    description: 'Introducing the next major version with Oxide engine, zero-config content detection, and CSS-first configuration.',
    author: 'Tailwind Labs',
    readingTimeMinutes: 10,
    mediaType: 'article',
    contentRawHtml: null,
    contentCleanMarkdown: null,
    coverImageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=modern%20CSS%20code%20editor%20interface%20dark%20theme%20utility%20classes%20color%20palette%20swatches&image_size=landscape_4_3',
    faviconUrl: null,
    assetStorageKey: null,
    status: 'active',
    isPinned: false,
    decayScore: 0.90,
    tags: [mockTags[6], mockTags[4]],
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'b_6',
    tenantId: 't_1',
    userId: 'u_1',
    collectionId: 'c_3',
    url: 'https://tokio.rs/blog/2024-03-announcing-tokio-1',
    canonicalUrl: null,
    domain: 'tokio.rs',
    title: 'Tokio 1.0 — An Async Runtime for Rust',
    description: 'The production-ready release of Tokio, the fastest async runtime in the Rust ecosystem.',
    author: 'Tokio Team',
    readingTimeMinutes: 15,
    mediaType: 'article',
    contentRawHtml: null,
    contentCleanMarkdown: null,
    coverImageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=rust%20tokio%20async%20runtime%20terminal%20dark%20theme%20green%20code%20syntax%20highlighting&image_size=landscape_4_3',
    faviconUrl: null,
    assetStorageKey: null,
    status: 'inbox',
    isPinned: false,
    decayScore: 0.78,
    tags: [mockTags[5]],
    createdAt: new Date('2024-03-06'),
    updatedAt: new Date('2024-03-06'),
  },
  {
    id: 'b_7',
    tenantId: 't_1',
    userId: 'u_1',
    collectionId: 'c_1',
    url: 'https://arxiv.org/abs/2301.13688',
    canonicalUrl: null,
    domain: 'arxiv.org',
    title: 'Zero-Knowledge Rollups Explained',
    description: 'Understanding ZK-Rollups: how they achieve scalability and privacy for Ethereum L2 transactions.',
    author: 'Ethereum Foundation',
    readingTimeMinutes: 25,
    mediaType: 'article',
    contentRawHtml: null,
    contentCleanMarkdown: null,
    coverImageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=blockchain%20zero%20knowledge%20proof%20mathematical%20equations%20dark%20background%20ethereum%20purple%20abstract&image_size=landscape_4_3',
    faviconUrl: null,
    assetStorageKey: null,
    status: 'active',
    isPinned: false,
    decayScore: 0.88,
    tags: [mockTags[3]],
    createdAt: new Date('2024-03-07'),
    updatedAt: new Date('2024-03-07'),
  },
  {
    id: 'b_8',
    tenantId: 't_1',
    userId: 'u_1',
    collectionId: 'c_2',
    url: 'https://dribbble.com/shots/popular',
    canonicalUrl: null,
    domain: 'dribbble.com',
    title: '2024 UI Design Trends — Dark Mode & Glassmorphism',
    description: 'A curated collection of trending UI designs featuring dark themes and frosted glass effects.',
    author: 'Dribbble',
    readingTimeMinutes: 5,
    mediaType: 'image',
    contentRawHtml: null,
    contentCleanMarkdown: null,
    coverImageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=glassmorphism%20UI%20dashboard%20dark%20mode%20frosted%20glass%20cards%20modern%20design%20purple%20gradient&image_size=landscape_16_9',
    faviconUrl: null,
    assetStorageKey: null,
    status: 'inbox',
    isPinned: false,
    decayScore: 0.72,
    tags: [mockTags[2]],
    createdAt: new Date('2024-03-08'),
    updatedAt: new Date('2024-03-08'),
  },
  {
    id: 'b_9',
    tenantId: 't_1',
    userId: 'u_1',
    collectionId: 'c_1',
    url: 'https://nextjs.org/blog/next-15',
    canonicalUrl: null,
    domain: 'nextjs.org',
    title: 'Next.js 15 — React 19, Turbopack Stable & Partial Prerendering',
    description: 'The latest release brings stable Turbopack, React 19 support, and game-changing partial prerendering.',
    author: 'Vercel Team',
    readingTimeMinutes: 14,
    mediaType: 'article',
    contentRawHtml: null,
    contentCleanMarkdown: null,
    coverImageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=nextjs%20logo%20dark%20background%20modern%20web%20framework%20abstract%20gradient%20orbs%20minimal&image_size=landscape_4_3',
    faviconUrl: null,
    assetStorageKey: null,
    status: 'inbox',
    isPinned: true,
    decayScore: 0.95,
    tags: [mockTags[0], mockTags[4]],
    createdAt: new Date('2024-03-09'),
    updatedAt: new Date('2024-03-09'),
  },
  {
    id: 'b_10',
    tenantId: 't_1',
    userId: 'u_1',
    collectionId: 'c_4',
    url: 'https://www.awwwards.com/websites/portfolio/',
    canonicalUrl: null,
    domain: 'awwwards.com',
    title: 'Awwwards — Best Portfolio Websites of 2024',
    description: 'The most innovative and beautifully crafted portfolio websites recognized by the Awwwards jury.',
    author: 'Awwwards',
    readingTimeMinutes: 7,
    mediaType: 'article',
    contentRawHtml: null,
    contentCleanMarkdown: null,
    coverImageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=award%20winning%20web%20design%20portfolio%20creative%20dark%20background%20artistic%20layout%20modern&image_size=landscape_16_9',
    faviconUrl: null,
    assetStorageKey: null,
    status: 'inbox',
    isPinned: false,
    decayScore: 0.65,
    tags: [mockTags[2]],
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'b_11',
    tenantId: 't_1',
    userId: 'u_1',
    collectionId: 'c_3',
    url: 'https://vitejs.dev/blog/announcing-vite5',
    canonicalUrl: null,
    domain: 'vitejs.dev',
    title: 'Vite 5 — Next Generation Frontend Tooling',
    description: 'Vite 5 brings Rollup 4, Node 18+ requirement, and improved environment API.',
    author: 'Evan You',
    readingTimeMinutes: 9,
    mediaType: 'article',
    contentRawHtml: null,
    contentCleanMarkdown: null,
    coverImageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=vite%20lightning%20fast%20build%20tool%20yellow%20purple%20gradient%20dark%20background%20modern%20minimal&image_size=landscape_4_3',
    faviconUrl: null,
    assetStorageKey: null,
    status: 'active',
    isPinned: false,
    decayScore: 0.82,
    tags: [mockTags[0], mockTags[4]],
    createdAt: new Date('2024-03-11'),
    updatedAt: new Date('2024-03-11'),
  },
  {
    id: 'b_12',
    tenantId: 't_1',
    userId: 'u_1',
    collectionId: 'c_1',
    url: 'https://simonwillison.net/2024/Mar/19/llm-prompt-injection/',
    canonicalUrl: null,
    domain: 'simonwillison.net',
    title: 'Understanding LLM Prompt Injection Attacks',
    description: 'A thorough exploration of how prompt injection works, why it matters, and current mitigation strategies.',
    author: 'Simon Willison',
    readingTimeMinutes: 20,
    mediaType: 'article',
    contentRawHtml: null,
    contentCleanMarkdown: null,
    coverImageUrl: 'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=prompt%20injection%20attack%20concept%20AI%20security%20dark%20terminal%20code%20warning%20red%20accents&image_size=landscape_4_3',
    faviconUrl: null,
    assetStorageKey: null,
    status: 'inbox',
    isPinned: false,
    decayScore: 0.70,
    tags: [mockTags[3], mockTags[1]],
    createdAt: new Date('2024-03-12'),
    updatedAt: new Date('2024-03-12'),
  },
];
